export const POST_MESSAGE_EVENT = {
  OPEN_CAMERA: 'OPEN_CAMERA',
  PICK_IMAGE: 'PICK_IMAGE',
  IMAGE_SELECTED: 'IMAGE_SELECTED',
  DOWNLOAD_IMAGE: 'DOWNLOAD_IMAGE',
  IMAGE_DOWNLOAD_RESPONSE: 'IMAGE_DOWNLOAD_RESPONSE',
  SHARE_TO_INSTAGRAM_STORY: 'SHARE_TO_INSTAGRAM_STORY',
  INSTAGRAM_SHARE_RESPONSE: 'INSTAGRAM_SHARE_RESPONSE',
  LOGIN_KAKAO: 'LOGIN_KAKAO',
  LOGIN_RESPONSE_KAKAO: 'LOGIN_RESPONSE_KAKAO',
  LOGIN_APPLE: 'LOGIN_APPLE',
  LOGIN_RESPONSE_APPLE: 'LOGIN_RESPONSE_APPLE',
  LOGOUT: 'LOGOUT',
  LOGOUT_RESPONSE: 'LOGOUT_RESPONSE',
  CAMERA_SHOT: 'CAMERA_SHOT',
  SEND_IMAGE_ECHO: 'SEND_IMAGE_ECHO',
  NOTIFICATION_ON: 'NOTIFICATION_ON',
  GET_MY_FCM_TOKEN: 'GET_MY_FCM_TOKEN',
  NOTIFICATION_OFF: 'NOTIFICATION_OFF',
  OPEN_INSTAGRAM: 'OPEN_INSTAGRAM',
  GET_MY_APP_VERSION: 'GET_MY_APP_VERSION',
  STORE_DEEP_LINK: 'STORE_DEEP_LINK',
} as const

// 메시지 상태 상수 추가
export const MESSAGE_STATUS = {
  IMAGES_SELECTED: 'images_selected',
  DOWNLOAD_COMPLETED: 'download_completed',
  DOWNLOAD_FAILED: 'download_failed',
  SHARE_COMPLETED: 'share_completed',
  SHARE_FAILED: 'share_failed',
} as const
